README.md
doc/source/design.rst
doc/source/developers.rst
doc/source/glossary.rst
doc/source/install.rst
doc/source/intro.rst
doc/source/litterature.rst
doc/source/protocol_suites.rst
doc/source/quickstart.rst

Just testing the workflow of using pull request.

Fixing typos and updating docs a bit.

---

src/main/java/dk/alexandra/fresco/lib/lp/EnteringVariableCircuit.java
src/main/java/dk/alexandra/fresco/lib/lp/LPFactory.java
src/main/java/dk/alexandra/fresco/lib/lp/LPFactoryImpl.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/AltInnerProductProtocolImpl.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/EntrywiseProductFactory.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/EntrywiseProductFactoryImpl.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/EntrywiseProductProtocol.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/EntrywiseProductProtocolImpl.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/InnerProductFactory.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/InnerProductFactoryImpl.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/InnerProductProtocol.java
src/main/java/dk/alexandra/fresco/lib/math/linalg/InnerProductProtocolImpl.java

Changed name of dot-product to entrywise product. Also made clarifying descriptions to both entrywise product and inner product and factories

Name change of DotProduct

---

doc/source/quickstart.rst

PS: It seems that the doc website is a little outdated.

fixed source code example in docs

---

pom.xml

Remove leading whitespace from pom.xml

---

src/main/java/dk/alexandra/fresco/demo/PrivateSetDemo.java
src/test/java/dk/alexandra/fresco/demo/SetIntersectionDemo.java

Currently not working with OT-Extension

Added set intersection demo

---

pom.xml
properties/db.properties
src/main/java/dk/alexandra/fresco/framework/sce/resources/storage/SQLStorage.java
src/main/java/dk/alexandra/fresco/framework/sce/resources/storage/StorageStrategy.java
src/test/java/dk/alexandra/fresco/framework/storage/TestStorage.java
src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzLPSolver2Parties.java
src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzLPSolver3Parties.java

Moved to h2 instead to enable embedded in-memory database testing.

Changed mysql connector to h2

---

src/main/java/dk/alexandra/fresco/framework/Reporter.java
src/main/java/dk/alexandra/fresco/framework/sce/SCE.java
src/main/java/dk/alexandra/fresco/framework/sce/SCEImpl.java
src/test/java/dk/alexandra/fresco/lib/arithmetic/ParallelAndSequenceTests.java
src/test/java/dk/alexandra/fresco/suite/spdz/TestParallelAndSequenceEval.java

Enabled the feature of running multiple applications in sequence or in parallel.

Run multiple applications

---

src/main/java/dk/alexandra/fresco/lib/lp/LPFactory.java
src/main/java/dk/alexandra/fresco/lib/lp/LPFactoryImpl.java
src/main/java/dk/alexandra/fresco/lib/lp/LPPrefix.java
src/main/java/dk/alexandra/fresco/lib/lp/LPSolverProtocol.java
src/main/java/dk/alexandra/fresco/lib/lp/SimpleLPPrefix.java
src/main/java/dk/alexandra/fresco/lib/lp/UpdateMatrixProtocol.java
src/main/java/dk/alexandra/fresco/lib/statistics/DEAPrefixBuilder.java
src/main/java/dk/alexandra/fresco/lib/statistics/DEASolver.java
src/main/java/dk/alexandra/fresco/suite/spdz/utils/PlainSpdzLPPrefix.java
src/test/java/dk/alexandra/fresco/lib/arithmetic/LPSolverTests.java

Revert "Exposed secret shared lambdas within the LP solver"

---

src/main/java/dk/alexandra/fresco/framework/network/ScapiNetworkImpl.java

Reverts aicis/fresco#67
Does not compile with the Scapi version FRESCO uses

Revert "Make master changes reflect in develop"

---

src/main/java/dk/alexandra/fresco/lib/helper/builder/AdvancedNumericBuilder.java
src/main/java/dk/alexandra/fresco/lib/helper/builder/ComparisonProtocolBuilder.java
src/main/java/dk/alexandra/fresco/lib/helper/builder/StatisticsProtocolBuilder.java
src/main/java/dk/alexandra/fresco/lib/math/integer/division/DivisionFactory.java
src/main/java/dk/alexandra/fresco/lib/math/integer/division/DivisionFactoryImpl.java
src/main/java/dk/alexandra/fresco/lib/math/integer/division/KnownDivisorProtocol.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/CovarianceFactory.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/CovarianceMatrixFactory.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/CovarianceMatrixProtocolImpl.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/CovarianceProtocolImpl.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/MeanFactory.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/MeanProtocolImpl.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/StatisticsFactoryImpl.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/VarianceFactory.java
src/main/java/dk/alexandra/fresco/lib/math/integer/stat/VarianceProtocolImpl.java
src/test/java/dk/alexandra/fresco/lib/arithmetic/AdvancedNumericTests.java
src/test/java/dk/alexandra/fresco/lib/math/integer/division/DivisionTests.java
src/test/java/dk/alexandra/fresco/lib/math/integer/stat/StatisticsTests.java
src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzAdvancedNumeric.java

The algorithm for division with known divisor has been improved. The maxBitLength parameter can be omitted and the algorithm handles negative numbers.

Improved division with known divisor

---

core/pom.xml
core/src/main/java/dk/alexandra/fresco/framework/Application.java
core/src/test/java/dk/alexandra/fresco/lib/bool/BasicBooleanTests.java
core/src/test/java/dk/alexandra/fresco/lib/crypto/BristolCryptoTests.java
core/src/test/java/dk/alexandra/fresco/lib/math/mult/BristolMultTests.java
core/src/test/java/dk/alexandra/fresco/suite/dummy/TestDummyProtocolSuite.java
pom.xml
suite/pom.xml
suite/spdz/pom.xml
suite/tinytables/pom.xml
suite/tinytables/src/main/java/dk/alexandra/fresco/suite/tinytables/prepro/TinyTablesPreproProtocolSuite.java
suite/tinytables/src/test/java/dk/alexandra/fresco/suite/tinytables/TestTinyTables.java

Fixed all but one test in tiny tables - that fails due to an error in the network?

Fix tinytables tests

---

google-code-style.xml

Common google code style for eclipse.

Google code style for eclipse.

---

core/src/main/java/dk/alexandra/fresco/framework/network/KryoNetNetwork.java
core/src/test/java/dk/alexandra/fresco/framework/network/ResourcePoolCreator.java

All tests go through using KryoNet locally on mac.

Fixed KryoNet test connection issues. 

---

core/src/main/java/dk/alexandra/fresco/framework/builder/ProtocolBuilderBinary.java
core/src/main/java/dk/alexandra/fresco/framework/builder/ProtocolBuilderNumeric.java
core/src/main/java/dk/alexandra/fresco/lib/debug/BinaryOpenAndPrint.java
core/src/main/java/dk/alexandra/fresco/lib/field/bool/generic/XnorFromXorAndNotProtocolImpl.java
core/src/main/java/dk/alexandra/fresco/lib/field/integer/BasicNumericFactory.java
core/src/main/java/dk/alexandra/fresco/lib/field/integer/generic/IOIntProtocolFactory.java
core/src/main/java/dk/alexandra/fresco/lib/helper/AlgebraUtil.java
core/src/main/java/dk/alexandra/fresco/lib/helper/ParallelProtocolProducer.java
core/src/main/java/dk/alexandra/fresco/lib/helper/ProtocolProducerCollection.java
core/src/main/java/dk/alexandra/fresco/lib/helper/SequentialProtocolProducer.java
core/src/main/java/dk/alexandra/fresco/lib/helper/SingleProtocolProducer.java
core/src/main/java/dk/alexandra/fresco/lib/helper/bristol/BristolCircuitParser.java
core/src/main/java/dk/alexandra/fresco/lib/helper/builder/AbstractProtocolBuilder.java
core/src/main/java/dk/alexandra/fresco/lib/helper/builder/NumericIOBuilder.java
core/src/main/java/dk/alexandra/fresco/lib/lp/OpenAndPrintProtocol.java
core/src/main/java/dk/alexandra/fresco/suite/dummy/arithmetic/DummyArithmeticFactory.java
core/src/main/java/dk/alexandra/fresco/suite/dummy/bool/DummyBuilderFactory.java
core/src/main/java/dk/alexandra/fresco/suite/dummy/bool/DummyFactory.java
core/src/test/java/dk/alexandra/fresco/framework/builder/ProtocolBuilderHelper.java
core/src/test/java/dk/alexandra/fresco/lib/arithmetic/BasicArithmeticTests.java
core/src/test/java/dk/alexandra/fresco/lib/bool/BasicBooleanTests.java
demos/common/src/main/java/dk/alexandra/fresco/demo/helpers/DemoNumericApplication.java
demos/common/src/main/java/dk/alexandra/fresco/demo/helpers/ProtocolBuilderHelper.java
demos/sum/src/main/java/dk/alexandra/fresco/demo/SumAndOutputApplication.java
suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzAddProtocolOld.java
suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzMultProtocolOld.java
suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzSubtractProtocolOld.java
suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/utils/SpdzFactory.java
suite/tinytables/src/main/java/dk/alexandra/fresco/suite/tinytables/online/TinyTablesFactory.java
suite/tinytables/src/main/java/dk/alexandra/fresco/suite/tinytables/prepro/TinyTablesPreproFactory.java

Cleaning up code byt removing deprecated methods and updating type signatures to make future work explicit

Minor updates for parallel protocol producer

---

core/pom.xml
core/src/main/java/dk/alexandra/fresco/framework/network/KryoNetNetwork.java
demos/common/src/main/java/dk/alexandra/fresco/demo/helpers/ResourcePoolHelper.java
pom.xml
scapiNetwork/pom.xml
scapiNetwork/src/main/java/dk/alexandra/fresco/network/ScapiNetworkImpl.java
scapiNetwork/src/test/java/dk/alexandra/fresco/comparison/ComparisonTests.java
scapiNetwork/src/test/java/dk/alexandra/fresco/dummy/AbstractDummyArithmeticTest.java
scapiNetwork/src/test/java/dk/alexandra/fresco/dummy/TestDummyArithmeticProtocolSuite.java
scapiNetwork/src/test/java/dk/alexandra/fresco/network/ResourcePoolCreator.java
scapiNetwork/src/test/java/dk/alexandra/fresco/network/TestScapiNetwork.java
scapiNetwork/src/test/java/dk/alexandra/fresco/network/TestScapiNetworkLayer.java
suite/tinytables/src/main/java/dk/alexandra/fresco/suite/tinytables/ot/base/BaseOTFactory.java

Instead, we include the dependency in TinyTables where it is used for OT and in the new project scapiNetwork where the network code now lies. A few tests using the network is also included.

Moved SCAPI out of the fresco core. 

---

core/src/test/java/dk/alexandra/fresco/lib/bool/BasicBooleanTests.java
core/src/test/java/dk/alexandra/fresco/suite/dummy/bool/AbstractDummyBooleanTest.java
core/src/test/java/dk/alexandra/fresco/suite/dummy/bool/TestDummyProtocolSuite.java

Added tests for issyes 172 and 173

Test dummy booleans 172 173

---

core/src/main/java/dk/alexandra/fresco/lib/lp/LPSolver.java
core/src/main/java/dk/alexandra/fresco/lib/math/integer/binary/RepeatedRightShift.java
core/src/test/java/dk/alexandra/fresco/framework/network/NetworkBatchDecoratorTest.java
core/src/test/java/dk/alexandra/fresco/framework/sce/evaluator/TestEvaluationStrategy.java
core/src/test/java/dk/alexandra/fresco/lib/collections/permute/TestWaksmanUtils.java
core/src/test/java/dk/alexandra/fresco/lib/lp/TestLpBuildingBlocks.java

Mixed bag of minor changes that should bring us to 100% coverage for core (combined with the other pull requests).
As far as I could see, the code in RepeatedRightShift could not be reached (atleast not if the class is accessed as it is supposed to be), but you might want to confirm.

Minor tests and refactoring

---

core/src/test/java/dk/alexandra/fresco/framework/sce/evaluator/TestEvaluationStrategy.java
core/src/test/java/dk/alexandra/fresco/lib/lp/TestLpBuildingBlocks.java

Two trivial tests to help test coverage %

Missing enum tests

---

core/pom.xml
core/src/main/java/dk/alexandra/fresco/framework/network/KryoNetNetwork.java
core/src/test/java/dk/alexandra/fresco/framework/network/TestKryoNetNetwork.java

Nikolai recently discovered a bug in KryoNetNetwork which this PR should fix. Multiple test runs at least confirms this, but since it was a deadlock issue, one cannot say for certain. With high probability though, it's fixed :)
Also, if someone can explain why using free ports for the test testKryoNetConnectInterrupt results in an internal BindException I will be very happy to hear the reason. Happens only during a complete test run, and I see no mentions in the test output of the port it is trying to bind to.

Kryonet refactor

---

core/src/main/java/dk/alexandra/fresco/framework/network/KryoNetNetwork.java
core/src/test/java/dk/alexandra/fresco/framework/network/TestKryoNetNetwork.java

Still cannot reproduce locally, so have to use Travis as check.

Resolve network test errors

---

core/src/main/java/dk/alexandra/fresco/framework/network/Network.java
tools/ot/src/main/java/dk/alexandra/fresco/tools/cointossing/CoinTossing.java
tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/otextension/BristolOtFactory.java
tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/otextension/BristolRotBatch.java
tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/otextension/RotFactory.java
tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/otextension/RotDemo.java

221 fix correlation error bug

---

suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/storage/TestStorage.java

These tests have been failing randomly in recent builds after we started using the AsyncNetwork. However, these tests should not have to use the Network as they are not network related. This PR makes all the tests run locally, which also speeds them up considerably.

Simplifies tests of spdz storage in TestStorage.java

---

core/src/test/java/dk/alexandra/fresco/lib/arithmetic/BasicArithmeticTests.java

A very small change to optimize the lots-of-mults test (one of the heavier tests).

Parallelizes opening in lots-of-mults in BasicArithmeticTests.java.

---

README.md
codecov.yml
core/src/test/java/dk/alexandra/fresco/framework/network/async/TestAsyncNetwork.java
demos/aes/Readme.md
doc/source/contributing.rst
doc/source/developers.rst
doc/source/index.rst
doc/source/install.rst
doc/source/intro.rst
doc/source/quickstart.rst

Adds the new logo to the front page. Also, fixes multiple minor typos and rephrases the docs a bit.
This fixes #242

Add logo to readthedocs and various minor fixes.

---

doc/source/install.rst
doc/source/protocol_suites.rst

Added a few lines to the docs on how to use a suite module in a custom project.

Update install section with suite info

---

core/src/main/java/dk/alexandra/fresco/framework/builder/numeric/BuilderFactoryNumeric.java
core/src/main/java/dk/alexandra/fresco/framework/builder/numeric/Collections.java
core/src/main/java/dk/alexandra/fresco/framework/builder/numeric/DefaultCollections.java
core/src/main/java/dk/alexandra/fresco/lib/collections/io/OpenList.java
core/src/main/java/dk/alexandra/fresco/lib/collections/io/OpenMatrix.java
core/src/main/java/dk/alexandra/fresco/lib/conditional/ConditionalSelectRow.java
core/src/main/java/dk/alexandra/fresco/lib/conditional/SwapNeighborsIf.java
core/src/main/java/dk/alexandra/fresco/lib/conditional/SwapRowsIf.java

This allows for more flexible types in the collection api

Introduced types in some collection calls

---

core/src/main/java/dk/alexandra/fresco/lib/lp/OptimalValue.java
core/src/main/java/dk/alexandra/fresco/lib/statistics/DeaSolver.java
core/src/test/java/dk/alexandra/fresco/lib/lp/LpBuildingBlockTests.java
core/src/test/java/dk/alexandra/fresco/lib/statistics/DeaSolverTests.java
suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/LPSolverTests.java

Allows to sort and rank the results post computation

Introduced the SInt values for numerator and denominator in LP

---

core/src/main/java/dk/alexandra/fresco/lib/real/SReal.java

Let SReal extend DRes

---

core/src/main/java/dk/alexandra/fresco/framework/builder/numeric/AdvancedNumeric.java
core/src/main/java/dk/alexandra/fresco/lib/math/integer/exp/ExponentiationOpenExponent.java
core/src/test/java/dk/alexandra/fresco/lib/math/integer/exp/ExponentiationTests.java

Fixes a bug pointed out on gitter where the exponentiation with and open exponent would fail with a `NullPointerException` when the exponent was a power of two. 
This closes #303

Exponentiation bug

---

core/src/main/java/dk/alexandra/fresco/framework/util/Drng.java
core/src/main/java/dk/alexandra/fresco/framework/util/DrngImpl.java
core/src/test/java/dk/alexandra/fresco/framework/util/TestDrngImpl.java
tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/PolySampler.java
tools/overdrive/src/test/java/dk/alexandra/fresco/overdrive/math/PolySamplerTest.java

Added Gaussian sampling to PolySampler. 
Created unit test for PolySampler.

Gaussian sampling

---

demos/psi/Makefile

Fixes #330 (assuming the flag was indeed not needed)

Remove -vt from psi demo Makefile

---

demos/aes/Makefile
demos/aggregation/Makefile
demos/distance/Makefile
demos/psi/Makefile
demos/sum/Makefile

This makes running the demos a little more visual, imo.

Make last demo processes run in foreground

---

core/src/main/java/dk/alexandra/fresco/lib/math/integer/sqrt/SquareRoot.java
core/src/main/java/dk/alexandra/fresco/lib/real/DefaultAdvancedRealNumeric.java
suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzAdvancedNumeric.java

Faster logarithms for fixed point numbers

Faster log

---

core/src/main/java/dk/alexandra/fresco/lib/real/DefaultLinearAlgebra.java
core/src/main/java/dk/alexandra/fresco/lib/real/RealLinearAlgebra.java
core/src/test/java/dk/alexandra/fresco/lib/real/LinearAlgebraTests.java

Use ArrayList instead of Vector

---

core/pom.xml
core/src/main/java/dk/alexandra/fresco/framework/network/socket/Connector.java
core/src/main/java/dk/alexandra/fresco/framework/network/socket/SocketNetwork.java
core/src/test/java/dk/alexandra/fresco/framework/network/socket/TestConnector.java
demos/aes/pom.xml
demos/aggregation/pom.xml
demos/common/pom.xml
demos/distance/pom.xml
demos/pom.xml
demos/psi/pom.xml
demos/sum/pom.xml
lib/bristol/pom.xml
lib/common/pom.xml
lib/dea/pom.xml
lib/debug/pom.xml
lib/fixed/pom.xml
lib/list/pom.xml
lib/lp/pom.xml
lib/mimc/pom.xml
lib/pom.xml
pom.xml
suite/pom.xml
suite/spdz/pom.xml
suite/spdz2k/pom.xml
suite/tinytables/pom.xml
tools/bitTriples/pom.xml
tools/commitment/pom.xml
tools/mascot/pom.xml
tools/ot/pom.xml
tools/pom.xml

Properly close all connections in the network when any non-recoverable exception occurs

Improve connection handling on Exceptions

---

core/src/main/java/dk/alexandra/fresco/framework/network/socket/Connector.java

Close sockets in the map when the thread gets interrupted (from a timeout).

Close connections on Interrupt

---

pom.xml

Fixes #416 
I have tested that tests go through with the updated version.

Bump Jacoco to 0.8.11

---

lib/common/src/main/java/dk/alexandra/fresco/lib/common/math/integer/ProductSIntList.java
lib/common/src/main/java/dk/alexandra/fresco/lib/common/math/integer/SumSIntList.java
lib/common/src/test/java/dk/alexandra/fresco/lib/common/math/integer/TestProductAndSum.java

Fixes #423.
Also implements more thorough testing of these calls.

 Product and Sum applications should return identity when given empty list as input 
