aicis/fresco

- src/main/java/dk/alexandra/fresco/framework/sce/evaluator/BatchedStrategy.java
- src/main/java/dk/alexandra/fresco/lib/helper/builder/NumericProtocolBuilder.java
- src/main/java/dk/alexandra/fresco/lib/lp/ExitingVariableCircuit.java
- src/main/java/dk/alexandra/fresco/lib/lp/LPFactory.java
- src/main/java/dk/alexandra/fresco/lib/lp/LPFactoryImpl.java
- src/main/java/dk/alexandra/fresco/lib/lp/LPSolverCircuit.java
- src/main/java/dk/alexandra/fresco/lib/math/integer/min/MinInfFracProtocol.java
- src/main/java/dk/alexandra/fresco/lib/math/integer/min/MinimumFractionProtocolImpl.java
- src/test/java/dk/alexandra/fresco/lib/arithmetic/BasicArithmeticTests.java
- src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzBasicArithmetic2Parties.java
- src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzBasicArithmetic3Parties.java
- src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzLPBuildingBlocks.java
This fixes an error that made the LP-Solver fail when used on sufficiently larger values. The cause of the turned out to be an unfortunate implementation that gave overflow in the method we used to find the minimum positive fraction in the exiting variable protocol.
Also so addresses #12 by fixing the batched evaluation strategy so that sent messages are immediately received.
> Lpsolver bugfix

- pom.xml
- src/main/java/dk/alexandra/fresco/demo/DistanceDemo.java
- src/main/java/dk/alexandra/fresco/framework/configuration/CmdLineUtil.java
- src/main/java/dk/alexandra/fresco/lib/lp/LPSolverProtocol.java
- src/main/java/dk/alexandra/fresco/suite/bgw/configuration/BgwConfiguration.java
- src/main/java/dk/alexandra/fresco/suite/bgw/configuration/BgwConfigurationFromProperties.java
- src/main/java/dk/alexandra/fresco/suite/dummy/DummyConfiguration.java
- src/main/java/dk/alexandra/fresco/suite/spdz/configuration/SpdzConfiguration.java
- src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzLPSolver2Parties.java
Fixes problems pointed out on the mailing list in the command line utility where configurations of most protocol suites was not done correctly. 
Additionally: 
- adds a simple demo application using the commandline utility. The demo application simply computes the distance between two points in two-dimensional space given by the parties. 
- fixes a problem that could cause tests to be run in parallel.
> Fix commandline utility

- src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzKnownSIntProtocol.java
- src/main/java/dk/alexandra/fresco/suite/spdz/utils/SpdzFactory.java
This is only an issue when we try to serialize the SpdzSInt, as the size constraints does not hold (mac grows too large), so we did not see this before now.
> We forgot modulus for the mac. Only does this for the share.

- src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzBasicArithmetic2Parties.java
Found this while browsing the arithmetic tests. This seemed to be a copy-paste error from the test above.
> Fix: ensure that test does what its name suggests.

- src/main/java/dk/alexandra/fresco/suite/spdz/evaluation/strategy/SpdzProtocolSuite.java
- src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzMacCheckProtocol.java
- src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzOutputProtocol.java
- src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzOutputToAllProtocol.java
MacChecks are now done after each batch if an outputgate is amongst the batch. This mitigates the attack vector previously exposed where an attacker could learn something about the other parties input after an opening - e.g. a branching depending on the output.
> Bugfix: SPDZ MAC checks

- src/main/java/dk/alexandra/fresco/framework/network/ScapiNetworkImpl.java
While experimenting with different network configurations, I've had this file cause exceptions on line 157 when it tries to cast a PlainTCPSocketChannel to a PlainChannel (which I expected would be a superclass of it, but apparently not). This commit applies the fix I found after some experimentation.
I'm not really familiar with SCAPI, so please don't merge this until somebody can reassure me that this is in fact the correct way to deal with this problem and won't, say, cause any security issues down the line.
> Fixes a crash bug caused by an incorrect cast.

- doc/source/quickstart.rst
When trying the example code from the quickstart documentation, I got a compilation error. This should fix that.
> Fix quickstart documentation: getRemainingArgs() no longer exists.

- src/main/java/dk/alexandra/fresco/framework/network/ScapiNetworkImpl.java
Reverts aicis/fresco#31
Does not compile with the version of SCAPI that FRESCO uses.
> Revert "Fixes a crash bug caused by an incorrect cast."

- core/src/main/java/dk/alexandra/fresco/framework/builder/ProtocolBuilderNumeric.java
- core/src/main/java/dk/alexandra/fresco/lib/helper/ParallelProtocolProducer.java
- core/src/main/java/dk/alexandra/fresco/lib/helper/SingleProtocolProducer.java
- suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/SpdzBuilder.java
- suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/gates/SpdzInputProtocol.java
Necessity when working with large, complex computations - i.e. huge LPSolvings.
> Let SingleProtocolProducer be a Computation to let it break chains of NativeProtocols

- core/src/main/java/dk/alexandra/fresco/lib/math/integer/sqrt/SquareRoot.java
- core/src/test/java/dk/alexandra/fresco/lib/math/integer/sqrt/SqrtTests.java
Sqrt only worked reliably when you specified the exact bit length of the input. It now works when you specify a maximum bit length.
> Make Square root work when not specifying exact bit length

- demos/aes/src/test/java/dk/alexandra/fresco/demo/TestAESDemo.java
- suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestBasicArithmeticWithEncryption.java
which should enable a complete test-run without changing Java's security policies.
> Disables secure channel testing

- core/src/main/java/dk/alexandra/fresco/lib/compare/MiscOIntGenerators.java
Changed implementation of getTwoPowersList to not modify a list that has been sublisted as changes to a backing list makes the sublist throw ConcurrentModificationExceptions.
See stacktrace below for an encountered problem. 
```
java.util.ConcurrentModificationException: null
at java.util.SubList.checkForComodification(Unknown Source)
at java.util.SubList.size(Unknown Source)
at dk.alexandra.fresco.lib.math.integer.linalg.InnerProductOpen.lambda$buildComputation$1(InnerProductOpen.java:26)
at dk.alexandra.fresco.framework.builder.ProtocolBuilderImpl.lambda$par$4(ProtocolBuilderImpl.java:115)
at dk.alexandra.fresco.framework.builder.BuildStepSingle.createNextStep(BuildStepSingle.java:28)
at dk.alexandra.fresco.framework.builder.BuildStep.createProducer(BuildStep.java:127)
at …
```
> Exception due to MiscOIntGenerator sublist

- demos/aes/pom.xml
The wrong capitalization in `aes/pom.xml` prevents the generated jar from running on case-sensitive file-systems (i.e., Linux).
> fix AesDemo mainClass in pom.xml

- core/src/test/java/dk/alexandra/fresco/lib/arithmetic/BasicArithmeticTests.java
- core/src/test/java/dk/alexandra/fresco/suite/dummy/arithmetic/TestDummyArithmeticProtocolSuite.java
- suite/spdz/src/main/java/dk/alexandra/fresco/suite/spdz/storage/SpdzMascotDataSupplier.java
- suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzBasicArithmetic2Parties.java
- suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/TestSpdzBasicArithmetic3Parties.java
Addresses issue #266. The mascot data supplier generates pre-processing material in batches and caches the results; this works correctly for party-independent material such as multiplication triples but does not work (w/o modification) for party-dependent input masks. This fix updates the mechanism for pre-generating and caching input masks per party (as opposed to in a single collection).
> 266 mascot input mask fix

- doc/source/protocol_suites.rst
This adds a very short description of the SPDZ2k protocol suite and a reference to the paper (which should be updated once the paper is published) to the Protocol Suites section on our readthedocs site.
This closes #260
> Adds a short description of the SPDZ2k to readthedocs

- core/src/main/java/dk/alexandra/fresco/framework/network/async/AsyncNetwork.java
- core/src/test/java/dk/alexandra/fresco/framework/network/async/TestAsyncNetwork.java
The tests used to have `Thread.sleep()` calls in order for other threads to catch up. This turns out
to be quite unreliable, particularly on Travis. 
In this PR we remove all sleeps and attempt to replace them by waiting for relevant futures to finish. 
This (hopefully) solves #274
> More stable AsyncNetwork tests by removing sleeps.

- core/src/main/java/dk/alexandra/fresco/framework/network/async/AsyncNetwork.java
- core/src/test/java/dk/alexandra/fresco/framework/network/async/TestAsyncNetwork.java
Attempts to fix a problem where the `receive` call on `AsynNetwork` would block forever. This could happen if a call to receive blocked waiting for a message but in the mean time the receiving thread finishes (e.g., by throwing an exception). 
Before we only checked if the `Receiver` had finished when entering the `receive` method. Now the receive call will periodically (every 100ms) re-check if the receiving thread has stopped.
Hopefully this should fix some of the occasional problems with the network and related tests.
> Attempt to make receive less likely to block

- core/src/main/java/dk/alexandra/fresco/lib/math/integer/division/KnownDivisor.java
- tools/overdrive/pom.xml
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/CoefficientRingPoly.java
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/EvaluationRingPoly.java
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/NaiveNnt.java
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/NntCt.java
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/NumberTheoreticTransform.java
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/RingPoly.java
- tools/overdrive/src/main/java/dk/alexandra/fresco/overdrive/math/package-info.java
- tools/overdrive/src/test/java/dk/alexandra/fresco/overdrive/math/CoefficientRingPolyTest.java
- tools/overdrive/src/test/java/dk/alexandra/fresco/overdrive/math/EvaluationRingPolyTest.java
- tools/overdrive/src/test/java/dk/alexandra/fresco/overdrive/math/NaiveNntTest.java
- tools/overdrive/src/test/java/dk/alexandra/fresco/overdrive/math/NntCtTest.java
Implements ring polynomials represented as straight forward coefficient lists and represented as a list of evaluations of the polynomial on which arithmetic can be done much more efficiently (in particular for multiplication). 
This PR also includes an implementation of the Number Theoretic Transform used to do the conversion between the two representations.
This closes #321
> Polynomial representations

- .gitlab-ci.yml
since `registry.gitlab.com/partisia/dockerimages/maven-jdk9:latest` is private this makes it very easy to override the `DOCKER_IMAGE` env var in gitlab and use an accessible image.
> configurable docker image for gitlab-ci

- pom.xml
fixes issues with running on newer JDKs,  
however requires Maven >= 3.0 (see https://github.com/jacoco/jacoco/releases).
if the Maven >= 3.0 is an issue then v0.8.2 could be used instead as it doesn't have that requirement yet.
> bump jacoco version to v0.8.3

- suite/spdz/src/test/java/dk/alexandra/fresco/suite/spdz/storage/TestSpdzStorage.java
This PR cleans up files created during file-based storage tests.
RIP `valid_ModP` ⚰️
> Cleans up after spdz filebased storage test

- core/src/main/java/dk/alexandra/fresco/lib/real/fixed/utils/NormalizeSInt.java
- core/src/test/java/dk/alexandra/fresco/lib/real/NormalizeTests.java
Fix a bug in the normalization function which computed the scaling factor wrong if the bit length was bigger than 32. The test is also extended to check both the scaling factor and the exponent.
> Fix bug in normalization

- core/src/main/java/dk/alexandra/fresco/framework/builder/numeric/AdvancedNumeric.java
- core/src/main/java/dk/alexandra/fresco/lib/math/integer/division/KnownDivisor.java
- core/src/test/java/dk/alexandra/fresco/lib/math/integer/division/DivisionTests.java
- core/src/test/java/dk/alexandra/fresco/suite/dummy/arithmetic/TestDummyArithmeticProtocolSuite.java
The old division protocol had a rather annoying requirement on the input sizes of both the dividend and divisor. This protocol simplifies this to allow the divisor to be of any size and the dividend to be up to half the max bit length.
> New division protocol with more predicitable output

- lib/common/src/main/java/dk/alexandra/fresco/lib/common/collections/Matrix.java
- lib/common/src/test/java/dk/alexandra/fresco/lib/common/collections/MatrixTest.java
It is more convenient to define a matrix by what the (i,j)'th entry looks like than by building rows, so we add a new constructor to the Matrix class which can do this.
> Create matrix with entry builder

- lib/common/src/main/java/dk/alexandra/fresco/lib/common/math/integer/binary/BitLength.java
In order to compute the bit length, fresco computes the entire bit string from right shifts. However, a more efficient method to do this is implemented to support fixed point arithmetic, so this pull request suggests that this more efficient method is also used to compute the bit length.
> Use norm to compute bit length

- .github/workflows/qa.yml
Fixes CI breaking for forks due to insufficient permissions.
> Fix CI breaking in Forks

- lib/common/src/main/java/dk/alexandra/fresco/lib/common/compare/Comparison.java
- lib/common/src/main/java/dk/alexandra/fresco/lib/common/compare/DefaultComparison.java
- lib/common/src/main/java/dk/alexandra/fresco/lib/common/compare/lt/LessThanZero.java
- lib/common/src/main/java/dk/alexandra/fresco/lib/common/math/integer/binary/NormalizeSInt.java
- lib/common/src/test/java/dk/alexandra/fresco/lib/common/compare/CompareTests.java
- lib/common/src/test/java/dk/alexandra/fresco/lib/common/compare/lt/LessThanZeroTests.java
Fixes [#427](https://github.com/aicis/fresco/issues/427)
> Changed compareLT and LessThanZero to take bitlength
